name: notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - binutils
  - flex
  - gfortran
  - gxx
  - libopenblas
  - make
  - patch
variables:
  JULIA_NUM_THREADS: 3
  OMP_NUM_THREADS: 1
