#!/bin/bash

set -xeou pipefail

dot_local_dir=${HOME}/.local
mkdir -p "${dot_local_dir}"

# Install AWS CLI
wget -qO- https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip >awscliv2.zip
unzip awscliv2.zip
aws/install --install-dir "${dot_local_dir}/share/aws-cli" --bin-dir "${dot_local_dir}/bin"
rm -rf awscliv2.zip aws/

src_home=${dot_local_dir}/src
bindx2_home=${src_home}/gmcgarragh/bindx2
xrtm_home=${src_home}/PeterSomkuti/xrtm

mkdir -p "${src_home}"

git clone https://github.com/gmcgarragh/bindx2 "${bindx2_home}"
cp "${bindx2_home}"/make.inc{.example,}
make -C "${bindx2_home}"

git clone https://github.com/PeterSomkuti/xrtm.git "${xrtm_home}"
git -C "${xrtm_home}" checkout b3aeace
cp "${xrtm_home}"/make.inc{.example,}
patch -d "${xrtm_home}" <make_xrtm.patch
# make -C "${xrtm_home}"

julia -e '
using Pkg;
Pkg.add(
    [
        "ArgParse",
        "Dates",
        "DocStringExtensions",
        "HDF5",
        "Interpolations",
        "LaTeXStrings",
        "LinearAlgebra",
        "Logging",
        "LoopVectorization",
        "Plots",
        "Printf",
        "ProgressMeter",
        "Statistics",
        "StatsBase",
        "Unitful"
    ]
)
'
